name=exit4067
version=1.0.0
author=karasExit <karas.dev32@gmail.com>
maintainer=karasExit <karas.dev32@gmail.com>
sentence=Библиотека для получения данных с аналогового мультиплексора hp4067
paragraph=Supports HTTP1.1 and you can do GET and POST.
category=Device Control
url=https://github.com/karasExit/exit4067
architectures=*
